name: .NET

on:
  push:
    branches:
      - develop
      - main
      - release
  pull_request:
    branches:
      - develop
      - main
      - release

jobs:
  build:
    strategy:
      matrix:
        image: 
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.image}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore ./Cnct/Cnct.sln
    - name: Build
      run: dotnet build --no-restore --no-incremental --configuration Release /WarnAsError ./Cnct/Cnct.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ./Cnct/Cnct.sln
    - name: Package with build number
      run: dotnet pack --no-build --configuration Release ./Cnct/Cnct.NetCore/Cnct.NetCore.csproj -p:BuildNumber=${{ github.run_number }} -o ./Cnct/Cnct.NetCore/nupkg/github
    - name: Package for main release
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet pack --no-build --configuration Release ./Cnct/Cnct.NetCore/Cnct.NetCore.csproj -o ./Cnct/Cnct.NetCore/nupkg/nuget
    - name: Publish as GitHub artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'ubuntu-latest' }}
      with:
        name: package-${{ github.run_id }}
        path: ./Cnct/Cnct.NetCore/nupkg/github/Cnct.*.nupkg
    - name: Publish to GitHub Packages
      if: ${{ github.event_name == 'push' && matrix.image == 'ubuntu-latest' }}
      run: dotnet nuget push ./Cnct/Cnct.NetCore/nupkg/github/Cnct.*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to NuGet.org
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.image == 'ubuntu-latest' }}
      run: dotnet nuget push ./Cnct/Cnct.NetCore/nupkg/nuget/Cnct.*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
