name: .NET

on:
  push:
    branches:
      - develop
      - main
      - release
  pull_request:
    branches:
      - develop
      - main
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Cnct/Cnct.sln
    - name: Build
      run: dotnet build --no-restore --no-incremental --configuration Release /WarnAsError ./Cnct/Cnct.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release ./Cnct/Cnct.sln
